name: 'OpenCover Badge Generator'
description: 'Reads an open cover xml file and generates a badge to use in readme file'
branding:
  icon: 'percent'
  color: 'yellow'
runs:
  using: 'node12'
  main: 'index.js'
