name: 'OpenCover Badge Generator'
description: 'Reads an open cover xml file and generates a badge to use in readme file'
author: 'Dan Petitt (Coderanger.com)'
inputs:
  path-to-opencover-xml:
    description: 'Path to the open cover xml file'
    required: true
  path-to-badges:
    description: 'Path where the line and branch coverage svgs would be saved; these will be saved with the names coverage-badge-line.svg and coverage-badge-branch.svg; if not specified the files will be saved into the project root'
    required: false
  minimum-coverage:
    description: 'Threshold percentage at which a red badge would appear'
    required: true
  commit-badges:
    description: 'Commit changed badges to repository'
    required: false
    default: true
  commit-branch-name:
    description: 'Specify alternative branch to commit changed badges into'
    required: false
  repo-token:
    description: 'Github repo token so that the changed file can be committed, like secrets.GITHUB_TOKEN'
    required: true
branding:
  icon: 'percent'
  color: 'yellow'
runs:
  using: 'node12'
  main: 'src/index.js'
