on: [push]

jobs:
  generate_badge:
    runs-on: ubuntu-latest
    name: Generates a badge
    steps:
      - name: OpenCover Badge Generator
        uses: danpetitt/open-cover-badge-generator-action@v1.0.2
      - uses: actions/upload-artifact@v1
        with:
          path-to-badges: ./
          path-to-opencover-xml: ./test/opencover.xml
          minimum-coverage: 75
          repo-token: ${{ secrets.GITHUB_TOKEN }}
